version: '3.8'

services:
  frontend:
    build:
      context: ./email-app-frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./email-app-backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/email_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=email_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
